development:
  app_name: My Shipit
  secret_key_base: ca3435f467123efdf0897d5616e3201f9aa7ec1bbf1416eb96ed517a2cfa11f7f76cbc96de5b486eb6195cf6f6876e421149023a66a9c1eb894dd4811dacac43
  host: 'http://localhost:3000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  app_name: My Shipit
  secret_key_base: 058028b349b71886fbd14bb0089d8d5fcc2a0c030f62cce7adec1c2aed0a2c1677e9fcb1c51c8f2988628d52241a9f5b22ed7c989d97b529cb2f198229c52a7f
  host: 'http://localhost:4000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  app_name: My Shipit
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  github:
    domain: # defaults to github.com
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    webhook_secret: <%= ENV['WEBHOOK_SECRET'] %>
    private_key: <%= ENV['PRIVATE_KEY'] %>
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.
